(fn main ()
    (Fn Void)
    (:: ((:: print (Fn String Void))
         (:: ((:: str (Fn Int String))
              (:: ((:: fib (Fn Int Int)) 12) Int))
             String))
        Void))

(fn fib (x)
  (Fn Int Int)
  (:: (if (:: ((:: < (Fn Int Int Bool)) (:: x Int) 2) Bool)
        (:: x Int)
        (:: ((:: + (Fn Int Int))
             (:: ((:: fib (Fn Int Int))
                  (:: ((:: - (Fn Int Int)) (:: x Int) 1) Int))
                 Int)
             (:: ((:: fib (Fn Int Int))
                  (:: ((:: - (Fn Int Int)) (:: x Int) 2) Int))
                 Int))
            Int))
       Int))
